### ISSUE TITLE
Cannot Test MBP Bird's eye view

### ISSUE THREAD

**Issue by ahartoch** [FootballAnalysis/footballanalysis#5]
Hi,

 I came across the repository and I wanted to give it a try as it looks very interesting for football analysis. I tried to execute the program, but I get a series of errors. Am I missing something? 

(/Volumes/LaCie/FootballOpenCV/footballana)@Alexs-MBP Bird's eye view % python3 main.py --source testvideo.mov --view
Yolo model loaded!
DeepSort model loaded!
Perspective Transform model loaded!
Traceback (most recent call last):
  File "/Volumes/LaCie/FootballOpenCV/FootballAnalysis/footballanalysis-main/Bird's eye view/main.py", line 127, in <module>
    main(opt)
  File "/Volumes/LaCie/FootballOpenCV/FootballAnalysis/footballanalysis-main/Bird's eye view/main.py", line 62, in main
    yoloOutput = detector.detect(frame)
  File "/Volumes/LaCie/FootballOpenCV/FootballAnalysis/footballanalysis-main/Bird's eye view/elements/yolo.py", line 41, in detect
    pred = self.yolo_model(img, augment=False)[0]
  File "/Volumes/LaCie/FootballOpenCV/footballana/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Volumes/LaCie/FootballOpenCV/FootballAnalysis/footballanalysis-main/Bird's eye view/yolov5/models/yolo.py", line 116, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/Volumes/LaCie/FootballOpenCV/FootballAnalysis/footballanalysis-main/Bird's eye view/yolov5/models/yolo.py", line 147, in forward_once
    x = m(x)  # run
  File "/Volumes/LaCie/FootballOpenCV/footballana/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Volumes/LaCie/FootballOpenCV/footballana/lib/python3.10/site-packages/torch/nn/modules/upsampling.py", line 154, in forward
    recompute_scale_factor=self.recompute_scale_factor)
  File "/Volumes/LaCie/FootballOpenCV/footballana/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'

**Comment by amirhossein-kz** [comment]
Dear @ahartoch 

Thank you for your interest in our project.  You need to downgrade your PyTorch version.
Try this:

```
pip install torchvision==0.10.1
pip install torch==1.9.1 
```

This will solve your problem.

**Comment by ahartoch** [comment]
Thanks for the response.

 

I grassroot coach with very little programming skills, by I love technology however at grassroot level it is unaffordable. This kind of solutions seem great. I need to do some research as I cannot downgrade the pythorch version as it will not work on an M1 Mac.

 

Great job by the way!

 

 

 

From: Amirhossein Kazerouni ***@***.***>
Reply to: FootballAnalysis/footballanalysis ***@***.***>
Date: Tuesday, 2 August 2022 at 14:02
To: FootballAnalysis/footballanalysis ***@***.***>
Cc: aha ***@***.***>, Mention ***@***.***>
Subject: Re: [FootballAnalysis/footballanalysis] Cannot Test MBP Bird's eye view (Issue #5)

 

Dear @ahartoch

Thank you for your interest in our project. You need to downgrade your PyTorch version.
Try this:
pip install torchvision==0.10.1
pip install torch==1.9.1 
This will solve your problem.
